version: "3.7"
services:
    frontend:
        user: "1000:1001"
        build:
            context: frontend/docker/development/nginx
        ports:
            - "8080:80"
        volumes:
            - ./frontend:/app:rw
